crystal-community/icr

src/icr/console.cr
This makes `^D` work, see #5.
Before:
```
$ echo 2+2 | ./bin/icr
=> 4
=> 4
=> 4
=> 4
…snip…
```
After:
```
$ echo 2+2 | ./bin/icr
=> 4
```
=> Exit if input is nil

.travis.yml
Well... this looks like a big problem. Seems like Crystal won't run on the ancient LLVM version anymore, and Ubuntu 12.04 on Travis doesn't provide any recent ones.
The Travis Crystal config for Ubuntu 14.04 [is broken](https://github.com/travis-ci/travis-ci/issues/5808)
Furthermore, even on Ubuntu 14.04 this whole setup did not work (same old linking errors) until I recompiled Crystal.
This is a complex file but I can't get it any smaller. Anyway, it [runs successfully](https://travis-ci.org/BlaXpirit/crystal-icr/builds/117702359)
=> Fix Travis CI setup

.travis.yml
Followup to https://github.com/greyblake/crystal-icr/pull/15 because the Travis build environment was fixed
=> Simplify Travis CI setup

Makefile
This is useful for downstream packages like Homebrew to be able to have a consistent interface to install files. It means if you added e.g. a manpage or additional binaries in future we won't miss them.
CC @genki and https://github.com/Homebrew/homebrew-core/pull/1579
=> Makefile: add install target with PREFIX.

Makefile
Otherwise they'll try to copy something that doesn't exist.
=> Makefile: install/reinstall depend on build.

spec/integration/icr_spec.cr, src/icr/command_stack.cr
You can now define records in ICR i thought i would have a go at adding it i've also included a  unit test which passes also.
Example:
[brian@orville crystal-icr]$ bin/icr 
icr(0.18.6) > record Person, first_name : String, last_name : String do
icr(0.18.6) >     
icr(0.18.6) >     def full_name
icr(0.18.6) >       "#{first_name} #{last_name}"
icr(0.18.6) >     end
icr(0.18.6) >     
icr(0.18.6) >   end
=> ok
icr(0.18.6) > 
icr(0.18.6) > a = Person.new("Mike", "Nog").full_name
=> "Mike Nog"
icr(0.18.6) > quit
[brian@orville crystal-icr]$ make test
/data2/crystal/bin/crystal build --release -o bin/icr src/icr/cli.cr 
Deprecation: The build command was renamed to compile and will be removed in a future version.
/data2/crystal/bin/crystal spec
................
Finished in 55.39 seconds
16 …
=> Added support for records and added unit test

README.md, spec/icr_spec.cr, spec/integration/icr_spec.cr, spec/spec_helper.cr, src/icr.cr, src/icr/cli.cr, src/icr/console.cr
These commits add in an optional `-r` or `--require` flag which allows you to load icr with a particular package required. As well as some additional specs 😄 
```text
$ icr -r colorize
icr(0.18.7) > "hello".colorize(:blue)
=> "hello"
```
Without using the `-r` flag, the `colorize` method would not exist
```text
$ icr
icr(0.18.7) > "hello".colorize(:blue)
undefined method 'colorize' for String
"hello".colorize(:blue)
^~~~~~~~
```
=> Adding a "require" flag

spec/spec_helper.cr, src/icr.cr, src/icr/executer.cr
With the latest Crystal release of 0.20.0, there's a few breaking changes causing this error:
```
Failed make install:
/usr/local/bin/crystal build --release -o bin/icr src/icr/cli.cr 
Error in src/icr/cli.cr:2: while requiring "../icr"
require "../icr"
^
in src/icr.cr:3: while requiring "io/memory_io": can't find file 'io/memory_io' relative to '/Users/jeremywoertink/Sites/bar.cr/lib/icr/src'
require "io/memory_io"
^
make: *** [build] Error 1
```
This PR fixes the compatibility error.
=> updating for Crystal 0.20 compatibility

README.md
Crystal 0.20.0 is now required:
> (breaking change) MemoryIO has been renamed to IO::Memory
=> Update prerequiste Crystal version in README to 0.20.0

spec/integration/icr_spec.cr
Once of the specs is failing when installing on Archlinux, this is because the error message was changed in a newer crystal version.
This PR should correct the spec to expect the correct error message now.
<details>
Failures:                                                                                                         
1) icr command errors prints runtime error without crashing               
Failure/Error: output.should match /invalid Int32: 5a \(ArgumentError\)/
Expected: "icr(0.22.0) > \"5a\".to_i\nInvalid Int32: 5a (ArgumentError)\n0x443f7b: *CallStack::unwind:Array(Pointer(Void)) at ??\n0x457875: to_i32 at /$sr/lib/crystal/string.cr 418:5\n0x45776c: to_i at /usr/lib/crystal/string.cr 319:5\n0x442350: __icr_exec__ at …
=> Fix: Cannot install aur package in Archlinux

Makefile, src/icr/executer.cr
Avoiding debugging info with `--no-debug` flag, improves compilation speed.
```
>>> time crystal hi.cr --no-debug
Hi ICR!
real    0m2.068s
user    0m2.327s
sys     0m0.300s
>>> time crystal hi.cr
Hi ICR!
real    0m2.270s
user    0m2.650s
sys     0m0.320s
```
Is about 200 ms faster with `--no-debug` flag
=> Add --no-debug flag to improve speed

spec/integration/icr_spec.cr, src/icr/command_stack.cr
This PR catches assignments to constants like
```ruby
A = 0
B=1
HTTP_STATUS      =    404
```
But it will still ignore constant usages like `IO::Memory.new` or `String.build`. This will also ignore when checking equality between 2 constants like `A == B`.
=> catch constant assignment and set it outside of the exec method. fixes #51

spec/integration/icr_spec.cr, src/icr/console.cr
Inspired by https://github.com/pry/pry/wiki/Special-Locals#Last_result
```crystal
icr(0.23.1) > a = 42
=> 42
icr(0.23.1) > __
=> 42
icr(0.23.1) > __ + 1
=> 43
icr(0.23.1) > 1 + __
=> 44
icr(0.23.1) > __.to_s
=> "44"
icr(0.23.1) > __.to_i
=> 44
icr(0.23.1) > inc = -> { __ + 1 }
=> #<Proc(Int32):0x1002ea350>
icr(0.23.1) > inc.call
=> 45
...
```
cc @jwoertink
=> Last result local '__'

README.md
Change the location to `/usr/local` as in OS X you won't have permission to write to `/usr/bin`
=> Location: /usr/bin -> /usr/local/bin

shard.yml
ICR is used as dependency on other shards, it allow to install without post-install issues.
```
$ amber new blog --template ecr --database sqlite --deps
...
Installing icr (0.3.0)
Postinstall make install
Failed make install:
/usr/bin/crystal build --release --no-debug -o bin/icr src/icr/cli.cr
mkdir -p /usr/local/bin
cp ./bin/icr /usr/local/bin
cp: cannot create regular file '/usr/local/bin/icr': Permission denied
make: *** [Makefile:13: install] Error 1
```
Also see: https://travis-ci.org/amberframework/amberframework.org/builds/294059765?utm_source=github_status&utm_medium=notification
=> Remove post-install script

README.md
The word 'a' was missing in a few sentences in the README.
=> Some small grammar fixes to README.md

spec/integration/icr_spec.cr, src/icr.cr, src/icr/cli.cr, src/icr/console.cr, src/icr/highlighter.cr
[![asciicast](https://asciinema.org/a/145523.png)](https://asciinema.org/a/145523)
=> Implement syntax highlight

README.md, src/icr/console.cr, src/icr/executer.cr
I've found it helpful to be able to turn the --debug style output on and off interactively, so this patch adds a "debug" command along the lines of "paste" to toggle the output off and on.
=> Add debug command to toggle debug output interactively.

.gitignore, spec/integration/icr_spec.cr, src/icr.cr, src/icr/executer.cr
https://github.com/crystal-lang/crystal/releases/tag/0.24.0 (pre-release)
Shouldn't be merge until the official release
=> Crystal next support

spec/integration/icr_spec.cr, src/icr/cli.cr, src/icr/console.cr
fixes #96
```
$ ./bin/icr
icr(0.24.2) >
icr(0.24.2) > ^D
$ ./bin/icr --prompt-mode simple
> a = 1
=> 1
> ^D
$ ./bin/icr --prompt-mode none
a = 1
=> 1
^D
$ ./bin/icr --prompt-mode no-such-mode
wrong prompt mode (ArgumentError)
from Icr::Console#prompt:String
from __crystal_main
from main
```
/cc @KINGSABRI
=> Add --prompt-mode flag

.gitignore, Makefile, shard.yml
Now that the [`shard.yml` SPEC][spec] supports specifying targets, it makes sense to implement the `build` target in the `Makefile` in terms of that.
[spec]: https://github.com/crystal-lang/shards/blob/master/SPEC.md
=> Use `shards build` in the `build` step

src/icr.cr
'tempfile' is no longer 'require'd.
It appears that 'tempfile' is either required by default or part of Crystal 0.27 core.  Removing the 'require' results in a successful compile and a working `icr`.
=> Remove 'tempfile'

.gitignore, spec/integration/icr_spec.cr, spec/spec_helper.cr, src/icr/cli.cr
In Crystal 0.32.0, File.expand_path was changed to no longer expand the tilde (\~) character by default. This causes icr to create a '~' directory in the current folder.
This change restores the old behavior by setting home: true.
Also includes a commit that adds /lib directory to gitignore.
=> Expand tilde in config path

src/icr/cli.cr
Time.now has been removed in Crystal 0.33.0
This PR replaces it with Time.local
=> replace Time.now with Time.local

src/icr/console.cr
Currently on error output is wrong:
With `--no-color` option everything is fine.
After fix:
=> fix output on error

src/icr/console.cr
This PR adds a magic #help comment that prints out every magic comment and what it does, and fixes a minor bug in the way errors are printed. The spec was not updated for the #help comment, since I assume the help message is subject to change.
=> add #help comment, fix #122

shard.yml
* Allowing from Crystal v0.33.0 to retain support as is.
* Attempted to run the built for this branch using Crystal v1.0.0 and the build is green.
=> Upgrade Crystal version in shard.yml to allow >= 0.33.0
